### ISSUE TITLE
Extend database with a boxoffice data

### ISSUE THREAD

**Issue by Japoivvb** [cesarorrr/Cesar_Rodriguez_uf3_p1#2]
Create a table boxoffices to track how much money movies earn, 
- define the fields that you consider required
- define foreign key that you consider required

Create a featurebranch to fix it

set label as development to be tracked

**Comment by cesarorrr** [comment]
@Japoivvb Done

**Comment by Japoivvb** [comment]
Done as it was requested, good approach to use foreach with current filmd id to fill the foreign key.
Excellent @cesarorrr
